# Carter Minter
## Week 10 - 03/27/2021
### Python Numpy - Processing Arrays

In [1]:
import numpy as np

In [2]:
my_list = [11,22,33,44,55,66,77]

print(my_list)

[11, 22, 33, 44, 55, 66, 77]


In [6]:
my_arr = np.array(my_list)

In [7]:
print(my_arr.dtype)

int32


In [9]:
fruits = ['orange', 'banana', 'mango', 'grape']

my_strArr = np.array(fruits)

In [10]:
print(my_strArr.dtype)

<U6


In [11]:
my_arr2 = np.array([11,22,33,44,55], dtype = 'S')

In [12]:
print(my_arr2.dtype)

|S2


In [14]:
my_arr2 = np.array([11,22,33,44,55], dtype = 'S')

print(my_arr2.dtype)

|S2


In [17]:
my_arr3 = np.array([5,6,7,8], dtype='i4')

In [18]:
print(my_arr3.dtype)

int32


In [24]:
my_errArr = np.array(['1','2','3','4','5'], dtype='i8')

In [25]:
print(my_errArr)

[1 2 3 4 5]


In [26]:
my_errArr = np.array(['1','2','c','4','5'], dtype='i8')

ValueError: invalid literal for int() with base 10: 'c'

In [29]:
scores = [78.5, 88.9, 90.3, 89.9]
my_arr = np.array(scores)

In [30]:
print(my_arr)

[78.5 88.9 90.3 89.9]


In [31]:
arr = my_arr.astype('i')

In [32]:
print(arr)

[78 88 90 89]


In [33]:
arr = np.array([1,0,0,3,4,5,6,7,0])

In [34]:
print(arr.dtype)

int32


In [35]:
bool_arr = arr.astype(bool)

In [36]:
print(arr)
print(bool_arr)

[1 0 0 3 4 5 6 7 0]
[ True False False  True  True  True  True  True False]


In [37]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1, lst2]

my_arr = np.array(my_list)

print(my_arr)
print(my_arr.ndim)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


In [56]:
#numpy built in functions to generate arrays from existing arrays
# copy and view, instead of using =

my_lst = [11,12,15,17]

arr = np.array(my_lst)
c_arr = arr.copy()

print(arr)
print(c_arr)

[11 12 15 17]
[11 12 15 17]


In [57]:
arr[2] = 4
print(arr)
print(c_arr)

[11 12  4 17]
[11 12 15 17]


In [58]:
#view
my_lst = [11,12,15,17]

arr = np.array(my_lst)
v_arr = arr.view()

print(arr)
print(v_arr)

[11 12 15 17]
[11 12 15 17]


In [59]:
arr[2] = 666
print(arr)
print(v_arr)

[ 11  12 666  17]
[ 11  12 666  17]


In [60]:
print(c_arr.base)
print(v_arr.base)

None
[ 11  12 666  17]


In [61]:
#shape gives the number of elements in each dimension

In [63]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1, lst2]

my_arr = np.array(my_list)
print(my_arr)
my_arr.shape

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


(2, 5)

In [64]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1, lst2]

my_arr = np.array(my_list)
print(my_arr)
print(my_arr.ndim)
my_arr.shape

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


(2, 5)

In [65]:
# returns 2 dimensions and each dimension has 5 elements 

In [67]:
arr = np.array(lst1, ndmin= 4)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[1 2 3 4 5]]]]
4
(1, 1, 1, 5)


In [68]:
arr = np.array(lst1, ndmin= 6)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[[1 2 3 4 5]]]]]]
6
(1, 1, 1, 1, 1, 5)


In [ ]:
# each index in the shape tells the number of elements in that dimension 