# Carter Minter
## Week 10 - 03/27/2021
### Python numpy info

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
# arrays and matrixes are the most important data structure for data files

In [4]:
#numerical python

In [5]:
# Unlike lists or processing, we can access and manipulate data fast with numpy

In [6]:
arr = np.array([1,2,3,4,5,6])

In [7]:
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr1 = np.array((1,2,3,4,5,6))

In [10]:
arr1

array([1, 2, 3, 4, 5, 6])

In [11]:
type(arr1)

numpy.ndarray

In [12]:
#0-D array 
arr2 = np.array(50)

In [13]:
arr2
print(arr2)

50


In [14]:
arr2

array(50)

In [15]:
# 1 - D arrays 
arr3 = np.array([1,2,3,4,5,6])
print(arr3)

[1 2 3 4 5 6]


In [16]:
#2- D array, matrix 
arr4 = np.array([[1,2,3,4,5,6], [11,22,33,44,55,66]])
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [17]:
#3 - D array
arr5 = np.array( [ [[1,2,3], [4,5,6]], [[11,22,33], [44,55,66]] ])
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [19]:
print(arr2.ndim)

0


In [20]:
print(arr3.ndim)

1


In [21]:
print(arr4.ndim)

2


In [22]:
print(arr5.ndim)

3


In [23]:
#Array indexing 
#access 1 d array
print(arr3)

[1 2 3 4 5 6]


In [25]:
print(arr3[1])

2


In [26]:
print(arr3[-1])

6


In [27]:
print(arr3[0] + arr3[3])

5


In [28]:
#Access 2D Array
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [29]:
#print 2nd element in first matrix 
print(arr4[0,1])

2


In [31]:
#print last element in 2nd matrix 
print(arr4[1,5])
print(arr4[1,-1])

66
66


In [35]:
#print 44 
print(arr4[1,-3])
print(arr4[1,3])

44
44


In [36]:
#print from a 3-D matrix 
print(arr5)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [37]:
print(arr5[0,1,1])

5


In [38]:
print(arr5[0,0,1])

2


In [39]:
print(arr5[1,1,2])

66


In [40]:
print(arr5[1,1,1])

55


In [41]:
print(arr5[1,0,-1])

33


In [42]:
marr = np.array([1,2,3,4,5], ndmin = 5)

In [43]:
print(marr)

[[[[[1 2 3 4 5]]]]]


In [45]:
marr.ndim

5

In [46]:
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [48]:
print(arr4[0][-1])

6


In [49]:
#slicing up arrays
#[start:end], end index is excluded 
#[start:end:step]
#default start is 0 [:end]
#[start:] end will be the length of the array

In [50]:
print(arr2)

50


In [51]:
print(arr3)

[1 2 3 4 5 6]


In [52]:
print(arr3[1:4])

[2 3 4]


In [53]:
print(arr3[3:])

[4 5 6]


In [54]:
#Slice elements from the beginning to index 3 (not included)
print(arr3[:3])

[1 2 3]


In [57]:
print(arr3)

[1 2 3 4 5 6]


In [59]:
#negative slicing - slice from index 3 to the end
print(arr3[-3:-1])

[4 5]


In [60]:
print(arr3[1:5:2])

[2 4]


In [61]:
print(arr3[1:5:1])

[2 3 4 5]


In [62]:
print(arr3)

[1 2 3 4 5 6]


In [63]:
print(arr3[1:5:3])

[2 5]


In [67]:
#return every other element in the array 
print(arr3[1:6:2])
print(arr3[0:6:2])
print(arr3[::2])

[2 4 6]
[1 3 5]
[1 3 5]


In [69]:
#slicing 2-D Arrays
print(arr4)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [70]:
print(arr4.ndim)

2


In [71]:
print(arr4[1,2])

33


In [72]:
#slice from index 1 to 3 
#this slices from the same matrix 
print(arr4[1,1:3])

[22 33]


In [73]:
#this slices the same piece from two arrays 
print(arr4[0:2,3])

[ 4 44]


In [74]:
print(arr4[:,3])

[ 4 44]


In [75]:
#1-3 in each list
print(arr4[:,1:3])

[[ 2  3]
 [22 33]]
