# Carter Minter
## Week 11 
### Python NumPy Universal Functions 

In [4]:
import numpy as np 

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]

z = []

for i, j in zip(arr1,arr2):
    z.append(i+j)
    
z

#adds both lists together

[12, 14, 16, 18, 20, 22, 24, 26]

In [5]:
#zip 

fname = ('Alice', 'Bill', 'Shaun')
lname = ('Oconnel', 'fugger', 'longskin')

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Oconnel'), ('Bill', 'fugger'), ('Shaun', 'longskin'))


In [6]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [8]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [11]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [18]:
arr1 = np.random.randn(10)
arr1

array([ 1.68472067, -0.67690552, -0.11333653,  1.45909952,  0.20136942,
       -1.5529726 ,  0.02031088, -2.09610278,  0.21988804,  1.13316339])

In [19]:
arr2 = np.random.randn(10)
arr2

array([-0.0129323 , -0.52520542,  1.10948129,  1.22327697, -0.51181762,
        1.19911358, -0.95104844,  0.61438021, -1.10628473,  0.21676158])

In [20]:
np.add(arr1,arr2)

array([ 1.67178837, -1.20211094,  0.99614476,  2.68237649, -0.3104482 ,
       -0.35385902, -0.93073755, -1.48172257, -0.88639669,  1.34992498])

In [21]:
np.maximum(arr1,arr2)

array([ 1.68472067, -0.52520542,  1.10948129,  1.45909952,  0.20136942,
        1.19911358,  0.02031088,  0.61438021,  0.21988804,  1.13316339])

In [23]:
#np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
np.where(arr)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [25]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [26]:
print(np.where(arr < 4,-1,10))

[[-1 -1 -1]
 [-1 10 10]
 [10 10 10]]


In [27]:
np.where((arr <4) & (arr>2), -1, -2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [30]:
#Using List Comprehension
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True, False, False, True, True])
print(arr1)
print(arr2)
print(arr_b)
print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False False  True  True]
[(1, 10, True), (2, 20, False), (3, 30, False), (4, 40, True), (5, 50, True)]


In [31]:
 arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 30, 4, 5]

In [33]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)
arr3

array([ 1, 20, 30,  4,  5])