# Carter Minter
## Week 11 
### Python NumPy Universal Functions 

In [2]:
import numpy as np 

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]

z = []

for i, j in zip(arr1,arr2):
    z.append(i+j)
    
z

#adds both lists together

[12, 14, 16, 18, 20, 22, 24, 26]

In [5]:
#zip 

fname = ('Alice', 'Bill', 'Shaun')
lname = ('Oconnel', 'fugger', 'longskin')

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Oconnel'), ('Bill', 'fugger'), ('Shaun', 'longskin'))


In [6]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [8]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [11]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [18]:
arr1 = np.random.randn(10)
arr1

array([ 1.68472067, -0.67690552, -0.11333653,  1.45909952,  0.20136942,
       -1.5529726 ,  0.02031088, -2.09610278,  0.21988804,  1.13316339])

In [19]:
arr2 = np.random.randn(10)
arr2

array([-0.0129323 , -0.52520542,  1.10948129,  1.22327697, -0.51181762,
        1.19911358, -0.95104844,  0.61438021, -1.10628473,  0.21676158])

In [20]:
np.add(arr1,arr2)

array([ 1.67178837, -1.20211094,  0.99614476,  2.68237649, -0.3104482 ,
       -0.35385902, -0.93073755, -1.48172257, -0.88639669,  1.34992498])

In [21]:
np.maximum(arr1,arr2)

array([ 1.68472067, -0.52520542,  1.10948129,  1.45909952,  0.20136942,
        1.19911358,  0.02031088,  0.61438021,  0.21988804,  1.13316339])

In [23]:
#np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
np.where(arr)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [25]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [26]:
print(np.where(arr < 4,-1,10))

[[-1 -1 -1]
 [-1 10 10]
 [10 10 10]]


In [27]:
np.where((arr <4) & (arr>2), -1, -2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [30]:
#Using List Comprehension
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True, False, False, True, True])
print(arr1)
print(arr2)
print(arr_b)
print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False False  True  True]
[(1, 10, True), (2, 20, False), (3, 30, False), (4, 40, True), (5, 50, True)]


In [31]:
 arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 30, 4, 5]

In [33]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)
arr3

array([ 1, 20, 30,  4,  5])

In [3]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,True]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [5]:
np.where([[True,False],[True,True]], [[5,6],[7,8]],[[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [6]:
from numpy.random import randn
arr = randn(5,5)
arr


array([[ 0.66818214,  1.31804078,  0.03465627,  1.53263234, -0.28927638],
       [ 0.27263521,  0.5199212 ,  1.51643608,  0.43860647, -1.85011553],
       [ 0.70550787,  0.41927194,  0.67108354,  0.76079073, -1.82647327],
       [ 1.94651204, -0.66084809, -1.2487596 ,  0.98575139, -1.44702716],
       [ 0.68299823, -0.45507088,  1.09648903, -0.06359267,  0.76759241]])

In [7]:
np.where(arr<0, 0, arr)

array([[0.66818214, 1.31804078, 0.03465627, 1.53263234, 0.        ],
       [0.27263521, 0.5199212 , 1.51643608, 0.43860647, 0.        ],
       [0.70550787, 0.41927194, 0.67108354, 0.76079073, 0.        ],
       [1.94651204, 0.        , 0.        , 0.98575139, 0.        ],
       [0.68299823, 0.        , 1.09648903, 0.        , 0.76759241]])

In [8]:
np.where(arr<0, "x", arr)

array([['0.6681821447143801', '1.3180407808816452',
        '0.03465627228042245', '1.5326323436177867', 'x'],
       ['0.27263521136114033', '0.5199212031340193', '1.516436075744557',
        '0.43860647444172757', 'x'],
       ['0.7055078749527353', '0.4192719351384567', '0.671083544990919',
        '0.760790728509417', 'x'],
       ['1.9465120351222054', 'x', 'x', '0.9857513914732446', 'x'],
       ['0.6829982259252476', 'x', '1.0964890275145864', 'x',
        '0.7675924085804919']], dtype='<U32')

In [9]:
np.where(arr>0, 'positive', arr)

array([['positive', 'positive', 'positive', 'positive',
        '-0.28927637760531894'],
       ['positive', 'positive', 'positive', 'positive',
        '-1.8501155297607368'],
       ['positive', 'positive', 'positive', 'positive',
        '-1.826473268820103'],
       ['positive', '-0.6608480857376589', '-1.248759603750309',
        'positive', '-1.4470271604424045'],
       ['positive', '-0.45507087616257447', 'positive',
        '-0.06359267494805546', 'positive']], dtype='<U32')

In [12]:
np.where(arr<0, 0,1)

array([[1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0],
       [1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [13]:
arr_b=np.array([[True,False,True,False,False]])
arr_b.any()

True

In [14]:
arr_b.all()

False

In [15]:
#clean data for duplicates 
fruits = np.array(['Apple', 'Apple', 'Mango', 'Apple', 'Mango', 'Cherry', 'Cherry'])
np.unique(fruits)

array(['Apple', 'Cherry', 'Mango'], dtype='<U6')

In [16]:
#search a list
np.in1d(['Apple', 'Cherry', 'Mango'], fruits)

array([ True,  True,  True])

In [19]:
#Statistical measures 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
arr.sum()

45

In [21]:
arr.sum(0)
#note this sums the first index 

array([12, 15, 18])

In [22]:
arr.sum(1)
#this sums across the array

array([ 6, 15, 24])

In [23]:
arr.sum(2)


AxisError: axis 2 is out of bounds for array of dimension 2

In [24]:
print(arr)
np.sum(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [25]:
print(arr)
np.sum(arr, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [26]:
#sum of everything 
print(arr)
np.sum(arr, axis=None)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [27]:
arr.mean()

5.0

In [28]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [29]:
print(arr)
arr.mean(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [32]:
np.mean(arr, axis=0)


array([4., 5., 6.])

In [33]:
np.mean(arr, axis=1)

array([2., 5., 8.])

In [37]:
arr.var()

6.666666666666667

In [38]:
arr.std()

2.581988897471611

In [39]:
arr = np.array([1,13,4,5,66,7,2,34,56,78,98,7,3])
arr.sort()
arr

array([ 1,  2,  3,  4,  5,  7,  7, 13, 34, 56, 66, 78, 98])

In [40]:
#identity array
i = np.eye(5)
i


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
a = np.arange(25).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
a*i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [43]:
i = np.eye(2)
a = np.arange(4).reshape((2,2))
a*i

array([[0., 0.],
       [0., 3.]])

In [44]:
m = np.mat([[1,2],[3,4]])

m

matrix([[1, 2],
        [3, 4]])

In [45]:
m * i
#matrix will not multiply as the same as an array

matrix([[1., 2.],
        [3., 4.]])

In [46]:
#Transpose 

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr)
print('-------------------')

t = arr.T
#this flips the array

t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
-------------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [47]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [48]:
arr.transpose(0,1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
arr.transpose(1,0)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [51]:
arr_3d = np.arange(20).reshape(2,5,2)
print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [53]:
arr_3d.transpose(0,1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [54]:
arr_3d.transpose(1,0,2)

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [55]:
np.random.random((4,4))

array([[0.72027517, 0.36365219, 0.48052804, 0.79484855],
       [0.67521536, 0.16617528, 0.23908877, 0.56400894],
       [0.88218296, 0.89231523, 0.02270436, 0.09437502],
       [0.50402459, 0.56802939, 0.29122278, 0.7168682 ]])

In [56]:
from numpy.random import random 
random((4,4))

array([[0.07485186, 0.65507299, 0.89901607, 0.25761103],
       [0.31559452, 0.42939988, 0.15599655, 0.39354109],
       [0.06785931, 0.11744601, 0.23687416, 0.52030286],
       [0.53898256, 0.85642239, 0.943498  , 0.05396972]])

In [57]:
from numpy.random import randn
randn(5,5)

array([[-0.10974149,  0.46243594,  0.16994263, -0.91573409, -0.11881257],
       [ 0.48969725, -1.40422612,  1.66763852,  1.20233008,  0.63353438],
       [-0.7231357 , -1.26559864, -1.26461043, -1.1512104 ,  0.45822134],
       [ 0.60004925,  0.77232432,  1.28365966,  0.06247153,  0.7148203 ],
       [ 0.20350733, -1.49033947,  2.28844445, -0.57517881,  0.3722601 ]])

In [58]:
randn(5)

array([-0.27145267, -1.59861034, -0.5423221 ,  0.15951064, -0.53281302])

In [60]:
np.random.randint(10,50)

47

In [62]:
website = 'https://numpy.org/doc/stable/reference/ufuncs.html'
import webbrowser

webbrowser.open(website)

True

In [63]:
import pandas as pd 