# Carter Minter 
## Week 11
### Python numpy creating, processing, transporting arrays

In [65]:
import numpy as np 
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


In [2]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
print(arr.ndim)
print(arr.dtype)

1
float64


In [6]:
arr = np.ones((5,5))

print(arr)
print(arr.ndim)
print(arr.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
float64


In [5]:
arr = np.zeros((5,5))

print(arr)
print(arr.ndim)
print(arr.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
float64


In [12]:
arr = np.empty((2,2))

print(arr)
print(arr.ndim)
print(arr.dtype)

[[0. 0.]
 [0. 0.]]
2
float64


In [9]:
arr = np.zeros((2,2))

print(arr)
print(arr.ndim)
print(arr.dtype)

[[0. 0.]
 [0. 0.]]
2
float64


In [19]:
arr = np.empty((3,3), dtype=int)

print(arr)
print(arr.ndim)
print(arr.dtype)

[[          0           0    28135456]
 [        468           0           0]
 [-2147483648           0           0]]
2
int32


In [24]:
#arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
np.arange(60)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [26]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [32]:
arr = np.arange(10,100,5)
print(arr)
print(arr.shape)
print(arr.dtype)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
(18,)
int32


In [33]:
arr = np.arange(1,13,1)
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [35]:
#reshape arrays 

#1D to 2-D
arr_2d = arr.reshape(3,4)

print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
arr_2d = arr.reshape(4,3)

print(arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [37]:
#reshape 1-D to 3-D

arr_3d = arr.reshape(3,2,2)

print(arr_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [44]:
arr_3d = arr.reshape(2,3,2)

print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [41]:
arr_2d = arr.reshape(5,3)

print(arr_2d)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [60]:
arr_2d = arr.reshape(4,3)

print(arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [61]:
# reshape is view or copy 
print(arr_2d.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [62]:
arr_3d = arr.reshape(2,2,-1)

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [67]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [68]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
#Iterating 1-D
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [69]:
for n in array:
    print(n)

0
1
2
3
4
5
6
7
8
9


In [72]:
#ITERATING 2-D  
arr = np.array([[1,2,3,4],[5,6,7,8]])

for n in arr:
    print(n)

[1 2 3 4]
[5 6 7 8]


In [73]:
for n in arr:
    for x in n:
        print(x)


1
2
3
4
5
6
7
8


In [78]:
#Iterating 3-D Arrays 

arr_3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr_3d)
print(arr_3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [82]:
for n3 in arr_3d:
    for n2 in n3:
        for n1 in n2:
            print(n1)


1
2
3
4
5
6
7
8
9
10
11
12


In [83]:
#nditer iterates on each scalar element in np array 
for n in np.nditer(arr_3d):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12


In [84]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
arr_2d[:,::2]

array([[1, 3],
       [5, 7]])

In [86]:
for n in np.nditer(arr_2d[:,::2]):
    print(n)

1
3
5
7


In [87]:
arr = np.arange(1,13,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [88]:
arr_2d * arr_2d

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [89]:
arr_2d - arr_2d

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [90]:
arr_2d + arr_2d

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [91]:
arr_2d ** arr_2d

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]], dtype=int32)

In [92]:
arr_2d ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [93]:
1 / arr_2d

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [94]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [95]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
arr[::3]

array([ 1,  4,  7, 10])

In [98]:
arr[5:]

array([ 6,  7,  8,  9, 10, 11, 12])

In [99]:
arr[0:6] = 100

In [100]:
arr

array([100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12])

In [101]:
import numpy as np

In [102]:
arr_2d = np.array([[5,10,15], [15,10,20], [20,35,30]])
print(arr_2d.shape)
print(arr_2d)


(3, 3)
[[ 5 10 15]
 [15 10 20]
 [20 35 30]]


In [103]:
arr_2d[1]

array([15, 10, 20])

In [104]:
arr_2d[1][0]

15

In [107]:
#slicing
arr_2d[:2,1:]

array([[10, 15],
       [10, 20]])

In [108]:
 arr_2d[2]

array([20, 35, 30])

In [109]:
arr_2d[2,-1]

30

In [111]:
arr3 = np.zeros((9,9))
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [112]:
arr3.shape

(9, 9)

In [113]:
arr.shape[0]

12

In [114]:
arr.shape[2]

IndexError: tuple index out of range

In [119]:
l = arr3.shape[0]

for idx in range(1):
    arr[idx]=10
    
arr3

array([[10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [117]:
for idx in range(1):
    arr3[idx]= idx *2
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [120]:
l = arr3.shape[0]

for idx in range(1):
    arr3[idx]= idx + 2 
    
arr3

array([[2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [121]:
arr3[1:7]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [122]:
arr[1,6,7]

IndexError: too many indices for array

In [123]:
arr[[3,5]]

array([100, 100])

In [125]:
#reshape 


arr = np.arange(45).reshape(9,5)

#output
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [126]:
arr_t = arr.T

#output
arr_t

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [127]:
np.dot(arr_t,arr)

array([[5100, 5280, 5460, 5640, 5820],
       [5280, 5469, 5658, 5847, 6036],
       [5460, 5658, 5856, 6054, 6252],
       [5640, 5847, 6054, 6261, 6468],
       [5820, 6036, 6252, 6468, 6684]])

In [128]:
arr_3d = np.arange(45).reshape(3,5,3)

arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [129]:
# swap axes 

arr  = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [130]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])